In [2]:
import numpy as np
import pandas as pd

In [3]:
l=[1,2,3,4,5]

#### Create a array from list

In [4]:
arr=np.array(l) #first method

In [5]:
type(arr)

numpy.ndarray

In [6]:
np.asarray(l) #second method

array([1, 2, 3, 4, 5])

In [7]:
l2=[[1,2,3],[2,4,6]]

In [8]:
arr2=np.asarray(l2)  #Creating 2d array

In [9]:
arr3=np.asanyarray(l)

In [10]:
arr3

array([1, 2, 3, 4, 5])

In [11]:
arr.ndim


1

In [12]:
arr2.ndim   #returns dimension of array

2

#### Creating a Matrix
###### Matric are only 2d whereas array can be multidimensional,minimum dimension of martrix is 2
###### matrix is a sub part of array

In [13]:
mat=np.matrix(l)  

#### Deep Copy

In [14]:
b=np.copy(arr)

In [15]:
b

array([1, 2, 3, 4, 5])

#### Creating matrix using a function

In [16]:
a=np.fromfunction(lambda i,j:i==j,(3,3)) # 3*3 matrix

In [17]:
a

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [18]:
b=np.fromfunction(lambda i,j:i*j,(3,3))

In [19]:
b

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

#### Creating An array from an iterable

In [20]:
iterable =(i*i for i in range(5))
np.fromiter(iterable,int)

array([ 0,  1,  4,  9, 16])

#### Creating array From String

In [21]:
np.fromstring('1,2,5,6,7',sep=',')

array([1., 2., 5., 6., 7.])

#### Size Of  An Array

In [22]:
arr.size 

5

In [23]:
arr2.size

6

### Shape Of An Array

In [24]:
arr2.shape #return (2,3) ie 2rows and 3 columns

(2, 3)

In [25]:
arr.shape

(5,)

#### Creating array from arange which take float also


In [ ]:
list(range(0,10))

In [ ]:
list(range(0,3.4))    #Gives error

In [ ]:
np.arange(1,5.7)

#### Creating aray upto the range and putting all decimal possible values

In [26]:
np.linspace(1,7)

array([1.        , 1.12244898, 1.24489796, 1.36734694, 1.48979592,
       1.6122449 , 1.73469388, 1.85714286, 1.97959184, 2.10204082,
       2.2244898 , 2.34693878, 2.46938776, 2.59183673, 2.71428571,
       2.83673469, 2.95918367, 3.08163265, 3.20408163, 3.32653061,
       3.44897959, 3.57142857, 3.69387755, 3.81632653, 3.93877551,
       4.06122449, 4.18367347, 4.30612245, 4.42857143, 4.55102041,
       4.67346939, 4.79591837, 4.91836735, 5.04081633, 5.16326531,
       5.28571429, 5.40816327, 5.53061224, 5.65306122, 5.7755102 ,
       5.89795918, 6.02040816, 6.14285714, 6.26530612, 6.3877551 ,
       6.51020408, 6.63265306, 6.75510204, 6.87755102, 7.        ])

In [27]:
np.logspace(1,5,10,base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

#### Creating an array with zeroes

In [28]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [29]:
np.zeros((3,2)) # 3  rows and 2 columns

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

#### Creating an array with ones

In [30]:
a=np.ones(6)

In [31]:
a+6 

array([7., 7., 7., 7., 7., 7.])

In [32]:
a*9

array([9., 9., 9., 9., 9., 9.])

In [33]:
np.ones((2,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

#### Create A Diagonal Matrix

In [34]:
z=np.eye(5)

In [35]:
pd.DataFrame(z)

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

#### Generating Random data

In [36]:
np.random.rand(2,6)

array([[0.9525406 , 0.79655303, 0.40483308, 0.35251693, 0.12324777,
        0.07327556],
       [0.57560623, 0.49556164, 0.06001561, 0.49218201, 0.39446432,
        0.14173294]])

In [ ]:
np.random.randn(2,6)

In [ ]:
np.random.randint(3,99)

#### Creating Array Using Randomrandint

In [ ]:
az=np.random.randint(1,15,(4,3))

#### Reshape The Array

In [ ]:
az.reshape(2,6)  #while reshaping make sure that elements should be equal=row*column

In [ ]:
az[az>7]  #return those element >2

In [ ]:
az

In [ ]:
az[0,[1,2]]  #returns 11,19 i.e from az row1 values at index 1,2

In [ ]:
az[1:3,[1,2]]

#### We can add/subtract/multiplication/division two arrray also

In [ ]:
a12=np.random.randint(1,5,(2,2))
a13=np.random.randint(1,8,(2,2))

In [ ]:
a12

In [ ]:
a13

In [ ]:
a12+a13

In [ ]:
a12-a13

In [ ]:
a12*a13

In [ ]:
a12/a13

In [ ]:
a12/0 #returns infinity(inf)

In [ ]:
#### Transpose Of A Matrix

In [ ]:
po=np.random.randint(1,6,(2,3))

In [ ]:
po

In [ ]:
po.T

### Broadcasting

In [ ]:
array=np.zeros((2,3))

In [ ]:
array

In [ ]:
array+5

In [ ]:
x=np.array([[1,2]]) #for row
z=np.asarray([1,2,3]) #for collumns

In [ ]:
array+x.T #Row wise addition

In [ ]:
bv=array+z #Column wise addition

In [ ]:
bv

### Array Manipulation

In [ ]:
array2=np.random.randint(1,6,(3,4))

In [ ]:
array2

In [ ]:
array2.flatten()

In [ ]:
np.expand_dims(array2,axis=1)  # From 2d array To 3d Array

In [196]:
np.repeat(array2,2)  #repeats the array elements

array([3, 3, 4, 4, 5, 5, 5, 5, 2, 2, 3, 3, 5, 5, 3, 3, 5, 5, 1, 1, 4, 4,
       3, 3])

#### Creates Diagonal Array With the elemments

In [199]:
np.diag(np.array([1,3,5]))

array([[1, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

### String Operation

In [205]:
st=np.asarray(['rishabh,hell'])

In [206]:
st

array(['rishabh,hell'], dtype='<U12')

In [207]:
np.char.upper(st)

array(['RISHABH,HELL'], dtype='<U12')

In [208]:
np.char.capitalize(st)

array(['Rishabh,hell'], dtype='<U12')

#### Mathematical Operation

In [39]:
m=np.random.randint(1,7,(3,4))

In [225]:
np.sin(m)

array([[-0.7568025 ,  0.14112001,  0.90929743,  0.84147098],
       [ 0.84147098, -0.95892427, -0.95892427, -0.95892427],
       [-0.95892427,  0.90929743,  0.14112001, -0.2794155 ]])

In [226]:
np.cos(m)

array([[-0.65364362, -0.9899925 , -0.41614684,  0.54030231],
       [ 0.54030231,  0.28366219,  0.28366219,  0.28366219],
       [ 0.28366219, -0.41614684, -0.9899925 ,  0.96017029]])

In [227]:
np.tan(m)

array([[ 1.15782128, -0.14254654, -2.18503986,  1.55740772],
       [ 1.55740772, -3.38051501, -3.38051501, -3.38051501],
       [-3.38051501, -2.18503986, -0.14254654, -0.29100619]])

In [228]:
np.log10(m)

array([[0.60205999, 0.47712125, 0.30103   , 0.        ],
       [0.        , 0.69897   , 0.69897   , 0.69897   ],
       [0.69897   , 0.30103   , 0.47712125, 0.77815125]])

In [229]:
np.exp(m)

array([[ 54.59815003,  20.08553692,   7.3890561 ,   2.71828183],
       [  2.71828183, 148.4131591 , 148.4131591 , 148.4131591 ],
       [148.4131591 ,   7.3890561 ,  20.08553692, 403.42879349]])

In [230]:
np.sqrt(m)

array([[2.        , 1.73205081, 1.41421356, 1.        ],
       [1.        , 2.23606798, 2.23606798, 2.23606798],
       [2.23606798, 1.41421356, 1.73205081, 2.44948974]])

In [231]:
np.power(m,2)

array([[16,  9,  4,  1],
       [ 1, 25, 25, 25],
       [25,  4,  9, 36]])

In [232]:
np.mean(m)

3.5

In [233]:
np.max(m)

6

In [234]:
np.min(m)

1

In [235]:
np.var(m)

2.75

In [41]:
m

array([[3, 2, 2, 3],
       [1, 6, 6, 1],
       [2, 5, 6, 5]])

In [43]:
np.sort(m)

array([[2, 2, 3, 3],
       [1, 1, 6, 6],
       [2, 5, 5, 6]])

In [65]:
array7=np.array([1,2,5,7,1,9])

In [66]:
array7

array([1, 2, 5, 7, 1, 9])

In [67]:
np.sort(array7)

array([1, 1, 2, 5, 7, 9])

#### Returns the index where the item need to be placed

In [70]:
np.searchsorted(array7,10)

6

#### Counts Non zero element

In [73]:
np.count_nonzero(array7)

6

#### Returns the index where the element is greater than inserted element

In [77]:
np.where(array7>8)

(array([5]),)

#### Extracts The data greater than 3 

In [79]:
np.extract(array7>3,array7)

array([5, 7, 9])

#### Byte Swappping

In [82]:
array7.byteswap()  #swaps the data with their byte in memory

array([ 72057594037927936, 144115188075855872, 360287970189639680,
       504403158265495552,  72057594037927936, 648518346341351424])

### View 

In [88]:
b=array7.view()  #view is like shallow copy only

In [89]:
b[0]=9

In [90]:
b

array([9, 2, 5, 7, 1, 9])

In [91]:
array7

array([9, 2, 5, 7, 1, 9])

### Matrix library

In [98]:
import numpy.matlib as nm

In [94]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [96]:
nm.ones((3,5))

matrix([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [97]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Numpy -Linear Algebra

In [101]:
array8=np.random.randint(1,8,(4,5))

In [107]:
array10=np.random.randint(1,9,(5,4))

In [108]:
array8

array([[4, 7, 3, 5, 2],
       [5, 1, 4, 4, 2],
       [4, 7, 1, 4, 3],
       [6, 4, 4, 3, 6]])

In [110]:
np.dot(array8,array10)

array([[ 73,  97,  96, 137],
       [ 48,  47,  65,  98],
       [ 68,  98,  94, 125],
       [ 70,  96, 102, 134]])

In [111]:
array8@array10

array([[ 73,  97,  96, 137],
       [ 48,  47,  65,  98],
       [ 68,  98,  94, 125],
       [ 70,  96, 102, 134]])